repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-added-large-files
        args:
          - --maxkb=1000
      - id: check-vcs-permalinks
      - id: check-merge-conflict
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: check-json
      - id: debug-statements
      - id: end-of-file-fixer