name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r dev_requirements.txt
          sudo apt update
          sudo apt install llvm-15 mlir-15-tools

      - name: Run tests
        run: |
          pytest tests/python
          lit tests/mlir
