name: pre-commit

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: filter changed files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            changed:
              - '**'
      
      - name: show changed files
        run: |
          echo "changed files: ${{ steps.filter.outputs.changed_files }}"
          
      - name: install pre-commit
        run: |
          pip install pre-commit

      - name: run pre-commit
        run: |
          echo ${{ steps.filter.outputs.changed_files }} | xargs pre-commit run --show-diff-on-failure --verbose --files
